const products = [
  {
    _id: '1',
    name: 'iPhone 13 Pro 256GB Memory',
    image: '/images/iphone.jpg',
    description: `The iPhone 13 Pro is Apple's smaller premium iPhone with a 6.1" screen size and for the first time in an iPhone, it comes with a 120Hz ProMotion display for super smooth scrolling. The list of innovations includes a more capable triple camera setup, with a wide, ultra-wide and zoom cameras, as well as a LiDAR scanner.`,
    brand: 'Apple',
    category: 'Electronics',
    price: 1199.99,
    countInStock: 3,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '2',
    name: 'CANON EOS 6D Mark II, 26.2 Mp, Wi-Fi, Bluetooth',
    image: '/images/camera.jpg',
    description:
      'The Canon EOS 6D Mark II camera puts full-frame performance into a compact, fully featured DSLR. With amazing image quality, fast and accurate autofocus and the versatility desired for numerous environments, the EOS 6D Mark II offers creative content makers a camera that’s as fun as it is powerful.',
    brand: 'Cannon',
    category: 'Electronics',
    price: 1499.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Microsoft Xbox Series S 512GB',
    image: '/images/xbox.jpg',
    description:
      'The next generation of gaming brings our largest digital launch library yet to our smallest Xbox ever. With more dynamic worlds, faster load times, and the addition of Xbox Game Pass (sold separately), the all-digital Xbox Series S is the best value in gaming.',
    brand: 'Xbox',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'RAZER Naga Pro Mouse',
    image: '/images/mouse.jpg',
    description:
      'Why specialize in one genre, when you can rule them all? Adapt to every game with the Razer Naga Pro',
    brand: 'Razer',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '5',
    name: 'APPLE Watch Series 7, GPS, 41mm Midnight Aluminium Case',
    image: '/images/smartwatch.jpg',
    description:
      'Apple Watch can do what your other devices can’t because it’s on your wrist',
    brand: 'Apple',
    category: 'Electronics',
    price: 499.99,
    countInStock: 5,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Razer Huntsman V2 Analog Keyboard',
    image: '/images/keyboard.jpg',
    description:
      'Enter a higher dimension of control with the Razer Huntsman V2 Analog—our first analog optical gaming keyboard. Armed with every feature you’d expect from a top-of-the-line design, you’ll want for nothing in your pursuit of victory.',
    brand: 'Razer',
    category: 'Electronics',
    price: 199.99,
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'APPLE AirPods Pro',
    image: '/images/airpods.jpg',
    description:
      'Active Noise Cancellation: Block out the noise for immersive sound. Or switch to Transparency mode to hear what’s happening around you',
    brand: 'Apple',
    category: 'Electronics',
    price: 199.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'OLED Smart LG 65A13LA 4k TV',
    image: '/images/tv.jpg',
    description:
      'Slim, elegant and prodigiously talented, the LG OLED65A13LA is the best 4K TV you can buy in 2021',
    brand: 'LG',
    category: 'Electronics',
    price: 2099.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products
